const actions = {
    CONNECTION_ESTABLISHED: "CONNECTION_ESTABLISHED",
    SUBSCRIBE_CHANNEL: "SUBSCRIBE_CHANNEL",
    UNSUBSCRIBE_CHANNEL: "UNSUBSCRIBE_CHANNEL",
    UPDATE_TICKER: "UPDATE_TICKER"
};

export default actions;