const actions = {
    ESTABLISH_CONNECTION: "ESTABLISH_CONNECTION",
    START_LISTEN: "START_LISTEN",
    SUBSCRIBE_CHANNEL: "SUBSCRIBE_CHANNEL",
    UNSUBSCRIBE_CHANNEL: "UNSUBSCRIBE_CHANNEL",
    UPDATE_TICKER: "UPDATE_TICKER"
};

export default actions;